// this is an example program of how to read an 
// ascii type spectrum file generated by SpecTcl
// currently it will work with a 1, 2, g1, g2, s type 
// spectrum from SpecTcl
// 
// Written by Mark Wallace (1/11/2003)

#include <fstream>
#include <iostream>

using namespace std;

  TH1F *hsource;
  TH1F *hTDC[60];
  TH1F *hTDCsum;


int go(){
  SumSpectrum("run420",52639);
  Output420();

  SumSpectrum("run417",87457);
  Output417();

  SumSpectrum("run414",45452);
  Output414();

  SumSpectrum("run412",61272);
  Output412();

  SumSpectrum("run413",31957);
  Output413();

}

int Output420(){

  hTDCsum->GetXaxis()->SetTitle("time in micro sec");
  hTDCsum->SetTitle("run420 background - NERO standalone - CRS veto");    
  hTDCsum->SetYTitle("counts/sec");


  hTDCsum->SetAxisRange(0,0.03,"y");
  gStyle->SetOptStat(1000001);
  hTDCsum->Draw();

  c1->SaveAs("CRS-test/run420.eps");

  hTDCsum->SetAxisRange(0,11,"y");
  hTDCsum->SetAxisRange(0,20,"x");
  hTDCsum->Draw();

  c1->SaveAs("CRS-test/run420-2.eps");

}

int Output417(){

  hTDCsum->GetXaxis()->SetTitle("time in micro sec");
  hTDCsum->SetTitle("run417 background - NERO standalone - no veto");    
  hTDCsum->SetYTitle("counts/sec");


  hTDCsum->SetAxisRange(0,0.03,"y");
  gStyle->SetOptStat(1000001);
  hTDCsum->Draw();

  c1->SaveAs("CRS-test/run417.eps");

  hTDCsum->SetAxisRange(0,11,"y");
  hTDCsum->SetAxisRange(0,20,"x");
  hTDCsum->Draw();

  c1->SaveAs("CRS-test/run417-2.eps");

}

int Output414(){

  hTDCsum->GetXaxis()->SetTitle("time in micro sec");
  hTDCsum->SetTitle("run414 background - NERO standalone - CRS veto");    
  hTDCsum->SetYTitle("counts/sec");


  hTDCsum->SetAxisRange(0,0.03,"y");
  gStyle->SetOptStat(1000001);
  hTDCsum->Draw();

  c1->SaveAs("CRS-test/run414.eps");

  hTDCsum->SetAxisRange(0,11,"y");
  hTDCsum->SetAxisRange(0,20,"x");
  hTDCsum->Draw();

  c1->SaveAs("CRS-test/run414-2.eps");

}

int Output412(){

  hTDCsum->GetXaxis()->SetTitle("time in micro sec");
  hTDCsum->SetTitle("run412 background - NERO Experiment mode");    
  hTDCsum->SetYTitle("counts/sec");

  gStyle->SetOptStat(1000001);
  hTDCsum->SetAxisRange(0,0.015,"y");
  hTDCsum->Draw();

  c1->SaveAs("CRS-test/run412.eps");

  hTDCsum->SetAxisRange(0,0.015,"y");
  hTDCsum->SetAxisRange(0,20,"x");
  gPad->Modified();
  hTDCsum->Draw();

  c1->SaveAs("CRS-test/run412-2.eps");

}

int Output413(){

  hTDCsum->GetXaxis()->SetTitle("time in micro sec");
  hTDCsum->SetTitle("run413 background - NERO Experiment mode");    
  hTDCsum->SetYTitle("counts/sec");

  gStyle->SetOptStat(1000001);
  hTDCsum->SetAxisRange(0,0.015,"y");
  hTDCsum->SetAxisRange(0,20,"x");
  hTDCsum->Draw();

  c1->SaveAs("CRS-test/run413.eps");

  hTDCsum->SetAxisRange(0,0.015,"y");
  hTDCsum->SetAxisRange(0,210,"x");
  gPad->Modified();
  hTDCsum->Draw();

  c1->SaveAs("CRS-test/run413-2.eps");

}


int SumSpectrum(TString runname, int runtime){

  for (int i=0;i<60;i++){
      hTDC[i] = new TH1F("TDC","TDC",1050,0,210);
      hTDC[i]->GetXaxis()->SetTitle("micro sec");
      hTDC[i]->SetTitle("TDC");   

  }
  hTDCsum = new TH1F("TDC sum","TDC sum",1050,0,210);
  hTDCsum->GetXaxis()->SetTitle("time in micro sec");
  hTDCsum->SetTitle("TDC "+ runname);    
  hTDCsum->SetYTitle("counts/sec");

  //quadA histo hTDC[0] .. hTDC[14]
  ReadIn(runname,"/quadA_1.dat", runtime, 0);
  ReadIn(runname,"/quadA_2.dat", runtime, 1);
  ReadIn(runname,"/quadA_3.dat", runtime, 2);
  ReadIn(runname,"/quadA_4.dat", runtime, 3);
  ReadIn(runname,"/quadA_5.dat", runtime, 4);
  ReadIn(runname,"/quadA_6.dat", runtime, 5);
  ReadIn(runname,"/quadA_7.dat", runtime, 6);
  ReadIn(runname,"/quadA_8.dat", runtime, 7);
  ReadIn(runname,"/quadA_10.dat", runtime, 8);
  ReadIn(runname,"/quadA_11.dat", runtime, 9);
  ReadIn(runname,"/quadA_12.dat", runtime, 10);
  ReadIn(runname,"/quadA_13.dat", runtime, 11);
  ReadIn(runname,"/quadA_14.dat", runtime, 12);
  ReadIn(runname,"/quadA_15.dat", runtime, 13);
  ReadIn(runname,"/quadA_16.dat", runtime, 14);

  //quadB histo hTDC[15] .. hTDC[29]
  ReadIn(runname,"/quadB_1.dat", runtime, 15);
  ReadIn(runname,"/quadB_2.dat", runtime, 16);
  ReadIn(runname,"/quadB_3.dat", runtime, 17);
  ReadIn(runname,"/quadB_4.dat", runtime, 18);
  ReadIn(runname,"/quadB_5.dat", runtime, 19);
  ReadIn(runname,"/quadB_6.dat", runtime, 20);
  ReadIn(runname,"/quadB_7.dat", runtime, 21);
  ReadIn(runname,"/quadB_8.dat", runtime, 22);
  ReadIn(runname,"/quadB_9.dat", runtime, 23);
  ReadIn(runname,"/quadB_10.dat", runtime, 24);
  ReadIn(runname,"/quadB_11.dat", runtime, 25);
  ReadIn(runname,"/quadB_12.dat", runtime, 26);
  ReadIn(runname,"/quadB_13.dat", runtime, 27);
  ReadIn(runname,"/quadB_14.dat", runtime, 28);
  ReadIn(runname,"/quadB_15.dat", runtime, 29);

  //quadChisto hTDC[30] .. hTDC[44]
  ReadIn(runname,"/quadC_1.dat", runtime, 30);
  ReadIn(runname,"/quadC_2.dat", runtime, 31);
  ReadIn(runname,"/quadC_3.dat", runtime, 32);
  ReadIn(runname,"/quadC_4.dat", runtime, 33);
  ReadIn(runname,"/quadC_5.dat", runtime, 34);
  ReadIn(runname,"/quadC_6.dat", runtime, 35);
  ReadIn(runname,"/quadC_7.dat", runtime, 36);
  ReadIn(runname,"/quadC_8.dat", runtime, 37);
  ReadIn(runname,"/quadC_9.dat", runtime, 38);
  ReadIn(runname,"/quadC_10.dat", runtime, 39);
  ReadIn(runname,"/quadC_11.dat", runtime, 40);
  ReadIn(runname,"/quadC_12.dat", runtime, 41);
  ReadIn(runname,"/quadC_13.dat", runtime, 42);
  ReadIn(runname,"/quadC_14.dat", runtime, 43);
  ReadIn(runname,"/quadC_15.dat", runtime, 44);

  //quadDhisto hTDC[45] .. hTDC[59]
  ReadIn(runname,"/quadD_1.dat", runtime, 45);
  ReadIn(runname,"/quadD_2.dat", runtime, 46);
  ReadIn(runname,"/quadD_3.dat", runtime, 47);
  ReadIn(runname,"/quadD_4.dat", runtime, 48);
  ReadIn(runname,"/quadD_5.dat", runtime, 49);
  ReadIn(runname,"/quadD_6.dat", runtime, 50);
  ReadIn(runname,"/quadD_7.dat", runtime, 51);
  ReadIn(runname,"/quadD_8.dat", runtime, 52);
  ReadIn(runname,"/quadD_9.dat", runtime, 53);
  ReadIn(runname,"/quadD_10.dat", runtime, 54);
  ReadIn(runname,"/quadD_11.dat", runtime, 55);
  ReadIn(runname,"/quadD_12.dat", runtime, 56);
  ReadIn(runname,"/quadD_13.dat", runtime, 57);
  ReadIn(runname,"/quadD_14.dat", runtime, 58);
  ReadIn(runname,"/quadD_15.dat", runtime, 59);



  //adding all TDC channels into hTDCsum histo...

  float value=0;
  float error=0;
  float valueSum=0;
  float errorSum=0;

  for (int binN=0;binN<1050;binN++){

    for(int Channel=0;Channel<60;Channel++){
      value=hTDC[Channel]->GetBinContent(binN);
      error=hTDC[Channel]->GetBinError(binN);

      valueSum=hTDCsum->GetBinContent(binN);
      errorSum=hTDCsum->GetBinError(binN);

      hTDCsum->SetBinContent(binN,valueSum+value);
      hTDCsum->SetBinError(binN,sqrt(errorSum**2 + error**2));

    }

  }

}




int ReadIn(TString runname, TString spectrum2, int runtime, int histo){

  float value=0;
  float error=0;

  TString spectrum="/TDC";
  TString runtemp =runname+spectrum+spectrum2;
  runname=runtemp;

  cout << runname << endl;

  readsource(runname,runtime);

  for (int i=0;i<1050;i++){

    value=hsource->GetBinContent(i);
    error=hsource->GetBinError(i);

    hTDC[histo]->SetBinContent(i,value);
    hTDC[histo]->SetBinError(i,error);

  }

}





int IntegratewithError(int start, int stop){
    float value=0;
    float error=0;
 for (int i=start;i<stop;i++){

    value=value + hTDCsum->GetBinContent(i);
    error=error + (hTDCsum->GetBinError(i))**2;

  }

  error = sqrt(error);

  cout << "Integral = " << value << " +/- " << error << endl;

  return 0;
}



int readsource(char* pFilename, int runsec) {
  
  char temp[900];
  TString title, xtitle, ytitle;
  TString xsizeS, ysizeS, specType;
  const char *tempchar;
  int xsize,ysize;
  float SpecTclVersion;
  int xch, ych;
  float value;
  char ch0;
  Int_t i=1;
  int exitflag=0;
  int specnum=0;
  


  // open the file
  ifstream file(pFilename, ios::in);
  
  file.getline(temp,900);
  while (exitflag == 0) {
    title = "";
    xtitle = "";
    ytitle = "";
    xsizeS = "";
    ysizeS = "";
    i=1;

    // unpacking the header 

    while (temp[i]!='"'){
      if (temp[i]=='-' || temp[i]=='.') {title += '_';
      i++;
      } else {title += temp[i]; 
      i++;
     }
    }

    i+=3;
    while (temp[i]!=' ' && temp[i]!=')'){xsizeS+=temp[i];i++;}
    if (temp[i]==' '){i++;
    while (temp[i]!=')'){ysizeS+=temp[i]; i++;}
    }
    tempchar = xsizeS;
    xsize = atoi(tempchar);
    tempchar = ysizeS;
    ysize = atoi(tempchar);    
    file.getline(temp,900);
    file >> SpecTclVersion;
    file.getline(temp,900);
    file >>  specType;
    file.getline(temp,900);
    file.getline(temp,900);
    i=2;
    while (temp[i]!='"'){xtitle += temp[i];i++;}
    i++;
    if (temp[i]==' '){i+=2;
      while (temp[i]!='"'){ytitle+=temp[i];i++;}
    }
    cout << "--------------------------------------------" << endl;
    cout << title << " "  << xsize << " " <<ysize << endl;
    cout << "SpecTcl Version " << SpecTclVersion ;
    cout << " Spectrum type " << specType << endl;
    cout << xtitle << " " << ytitle << endl;
    file.getline(temp,900);
    cout << temp << endl;
    file.getline(temp,900);
    cout << temp << endl;

    cout << "end of reading header" << endl;
    


    // here is where I define the spectrum based on 
       // the info in the header


      hsource = new TH1F(title,title,xsize,0,xsize-1);
      hsource->GetXaxis()->SetTitle(xtitle);
      hsource->SetTitle("Run with source");    
      //     hcorr = new TH1F("corr.","corr.",xsize,0,xsize-1);

    
    
    xch =0;


    // here is where we fill the histogram

    while(xch != -1) {
      if (specType=="1" || specType=="g1") {
    	file >> ch0 >> xch >> ch0 >> value;
	hsource->Fill(xch,value/runsec);
	hsource->SetBinError(xch,sqrt(value)/runsec);
      } else {
	file >> ch0 >> xch >> ch0 >> value;
      }
    }
    file.getline(temp,900);
    file.getline(temp,900);
    int length = strlen(temp);
    if (length < 1) {exitflag=1;} 
  }
  file.close();


  //Draw histogram.

  //  hsource->Draw();
  //  gPad->SetLogy(1);
  //  gPad->Modified();



  return 0;
}


