// this is an example program of how to read an 
// ascii type spectrum file generated by SpecTcl
// currently it will work with a 1, 2, g1, g2, s type 
// spectrum from SpecTcl
// 
// Written by Mark Wallace (1/11/2003)

#include <fstream>
#include <iostream>

using namespace std;


  TH1F *hbackgr;
  TH1F *hsource;
  TH1F *hcorr;
  TH1F *hTDCsum;

int Output417(){

  hTDCsum = new TH1F("TDC sum","TDC sum",1050,0,209);
  hTDCsum->GetXaxis()->SetTitle("time in micro sec");
  hTDCsum->SetTitle("run417 background - NERO standalone - no veto");    
  hTDCsum->SetYTitle("counts/sec");

  float value=0;
  float error=0;


  for (int i=0;i<1025;i++){

    value=hsource->GetBinContent(i);
    error=hsource->GetBinError(i);

    hTDCsum->SetBinContent(i,value);
    hTDCsum->SetBinError(i,error);

  }

  hTDCsum->SetAxisRange(0,0.03,"y");
  hTDCsum->Draw();

  c1->SaveAs("CRS-test/run417.jpg");

}

int Output412(){

  hTDCsum = new TH1F("TDC sum","TDC sum",1050,0,209);
  hTDCsum->GetXaxis()->SetTitle("time in micro sec");
  hTDCsum->SetTitle("run412 background - NERO Experiment mode");    
  hTDCsum->SetYTitle("counts/sec");

  float value=0;
  float error=0;


  for (int i=0;i<1025;i++){

    value=hsource->GetBinContent(i);
    error=hsource->GetBinError(i);

    hTDCsum->SetBinContent(i,value);
    hTDCsum->SetBinError(i,error);

  }

  hTDCsum->SetAxisRange(0,0.03,"y");
  hTDCsum->Draw();

  c1->SaveAs("CRS-test/run412.jpg");

  hTDCsum->SetAxisRange(0,0.015,"y");
  gPad->Modified();
  c1->SaveAs("CRS-test/run412-2.jpg");
}


int Output418(){

  hTDCsum = new TH1F("TDC sum","TDC sum",1050,0,209);
  hTDCsum->GetXaxis()->SetTitle("time in micro sec");
  hTDCsum->SetTitle("run418 background - NERO Standalone - CRS veto");    
  hTDCsum->SetYTitle("counts/sec");

  float value=0;
  float error=0;


  for (int i=0;i<1025;i++){

    value=hsource->GetBinContent(i);
    error=hsource->GetBinError(i);

    hTDCsum->SetBinContent(i,value);
    hTDCsum->SetBinError(i,error);

  }

  hTDCsum->SetAxisRange(0,0.03,"y");
  hTDCsum->Draw();

  c1->SaveAs("CRS-test/run418.jpg");

  hTDCsum->SetAxisRange(0,0.015,"y");
  gPad->Modified();
  c1->SaveAs("CRS-test/run418-2.jpg");
}


int Output420(){

  hTDCsum = new TH1F("TDC sum","TDC sum",1050,0,209);
  hTDCsum->GetXaxis()->SetTitle("time in micro sec");
  hTDCsum->SetTitle("run420 background - NERO standalone - CRS veto");    
  hTDCsum->SetYTitle("counts/sec");

  float value=0;
  float error=0;


  for (int i=0;i<1025;i++){

    value=hsource->GetBinContent(i);
    error=hsource->GetBinError(i);

    hTDCsum->SetBinContent(i,value);
    hTDCsum->SetBinError(i,error);

  }

  hTDCsum->SetAxisRange(0,0.03,"y");
  hTDCsum->Draw();

  c1->SaveAs("CRS-test/run420.jpg");

  hTDCsum->SetAxisRange(0,11,"y");
  hTDCsum->SetAxisRange(0,20,"x");
  hTDCsum->Draw();

  c1->SaveAs("CRS-test/run420-2.jpg");

}



int SumSpectrum(TString runname, int runtime){

  float integralquadA=0;
  float integralquadB=0;
  float integralquadC=0;
  float integralquadD=0;
  TString spectrum="/TDC";
  TString runtemp =runname+spectrum;
  runname=runtemp;


  readsource(runname+"/quadA_1.dat",runtime);

  readbackgr(runname+"/quadA_2.dat",runtime);
  (*hsource)=(*hsource)+(*hbackgr);
  readbackgr(runname+"/quadA_3.dat",runtime);
  (*hsource)=(*hsource)+(*hbackgr);
  readbackgr(runname+"/quadA_4.dat",runtime);
  (*hsource)=(*hsource)+(*hbackgr);
  readbackgr(runname+"/quadA_5.dat",runtime);
  (*hsource)=(*hsource)+(*hbackgr);
  readbackgr(runname+"/quadA_6.dat",runtime);
  (*hsource)=(*hsource)+(*hbackgr);
  readbackgr(runname+"/quadA_7.dat",runtime);
  (*hsource)=(*hsource)+(*hbackgr);
  readbackgr(runname+"/quadA_8.dat",runtime);
  (*hsource)=(*hsource)+(*hbackgr);
  readbackgr(runname+"/quadA_9.dat",runtime);
  (*hsource)=(*hsource)+(*hbackgr);
  readbackgr(runname+"/quadA_10.dat",runtime);
  (*hsource)=(*hsource)+(*hbackgr);
  readbackgr(runname+"/quadA_11.dat",runtime);
  (*hsource)=(*hsource)+(*hbackgr);
  readbackgr(runname+"/quadA_12.dat",runtime);
  (*hsource)=(*hsource)+(*hbackgr);
  readbackgr(runname+"/quadA_13.dat",runtime);
  (*hsource)=(*hsource)+(*hbackgr);
  readbackgr(runname+"/quadA_14.dat",runtime);
  (*hsource)=(*hsource)+(*hbackgr);
  readbackgr(runname+"/quadA_15.dat",runtime);
  (*hsource)=(*hsource)+(*hbackgr);
  readbackgr(runname+"/quadA_16.dat",runtime);
  (*hsource)=(*hsource)+(*hbackgr);

  integralquadA=hsource->Integral(0,4096);

  readbackgr(runname+"/quadB_1.dat",runtime);
  (*hsource)=(*hsource)+(*hbackgr);
  readbackgr(runname+"/quadB_2.dat",runtime);
  (*hsource)=(*hsource)+(*hbackgr);
  readbackgr(runname+"/quadB_3.dat",runtime);
  (*hsource)=(*hsource)+(*hbackgr);
  readbackgr(runname+"/quadB_4.dat",runtime);
  (*hsource)=(*hsource)+(*hbackgr);
  readbackgr(runname+"/quadB_5.dat",runtime);
  (*hsource)=(*hsource)+(*hbackgr);
  readbackgr(runname+"/quadB_6.dat",runtime);
  (*hsource)=(*hsource)+(*hbackgr);
  readbackgr(runname+"/quadB_7.dat",runtime);
  (*hsource)=(*hsource)+(*hbackgr);
  readbackgr(runname+"/quadB_8.dat",runtime);
  (*hsource)=(*hsource)+(*hbackgr);
  readbackgr(runname+"/quadB_9.dat",runtime);
  (*hsource)=(*hsource)+(*hbackgr);
  readbackgr(runname+"/quadB_10.dat",runtime);
  (*hsource)=(*hsource)+(*hbackgr);
  readbackgr(runname+"/quadB_11.dat",runtime);
  (*hsource)=(*hsource)+(*hbackgr);
  readbackgr(runname+"/quadB_12.dat",runtime);
  (*hsource)=(*hsource)+(*hbackgr);
  readbackgr(runname+"/quadB_13.dat",runtime);
  (*hsource)=(*hsource)+(*hbackgr);
  readbackgr(runname+"/quadB_14.dat",runtime);
  (*hsource)=(*hsource)+(*hbackgr);
  readbackgr(runname+"/quadB_15.dat",runtime);
  (*hsource)=(*hsource)+(*hbackgr);
  readbackgr(runname+"/quadB_16.dat",runtime);
  (*hsource)=(*hsource)+(*hbackgr);

  integralquadB=hsource->Integral(0,4096)-integralquadA;

  readbackgr(runname+"/quadC_1.dat",runtime);
  (*hsource)=(*hsource)+(*hbackgr);
  readbackgr(runname+"/quadC_2.dat",runtime);
  (*hsource)=(*hsource)+(*hbackgr);
  readbackgr(runname+"/quadC_3.dat",runtime);
  (*hsource)=(*hsource)+(*hbackgr);
  readbackgr(runname+"/quadC_4.dat",runtime);
  (*hsource)=(*hsource)+(*hbackgr);
  readbackgr(runname+"/quadC_5.dat",runtime);
  (*hsource)=(*hsource)+(*hbackgr);
  readbackgr(runname+"/quadC_6.dat",runtime);
  (*hsource)=(*hsource)+(*hbackgr);
  readbackgr(runname+"/quadC_7.dat",runtime);
  (*hsource)=(*hsource)+(*hbackgr);
  readbackgr(runname+"/quadC_8.dat",runtime);
  (*hsource)=(*hsource)+(*hbackgr);
  readbackgr(runname+"/quadC_9.dat",runtime);
  (*hsource)=(*hsource)+(*hbackgr);
  readbackgr(runname+"/quadC_10.dat",runtime);
  (*hsource)=(*hsource)+(*hbackgr);
  readbackgr(runname+"/quadC_11.dat",runtime);
  (*hsource)=(*hsource)+(*hbackgr);
  readbackgr(runname+"/quadC_12.dat",runtime);
  (*hsource)=(*hsource)+(*hbackgr);
  readbackgr(runname+"/quadC_13.dat",runtime);
  (*hsource)=(*hsource)+(*hbackgr);
  readbackgr(runname+"/quadC_14.dat",runtime);
  (*hsource)=(*hsource)+(*hbackgr);
  readbackgr(runname+"/quadC_15.dat",runtime);
  (*hsource)=(*hsource)+(*hbackgr);
  readbackgr(runname+"/quadC_16.dat",runtime);
  (*hsource)=(*hsource)+(*hbackgr);

  integralquadC=hsource->Integral(0,4096)-integralquadA-integralquadB;

  readbackgr(runname+"/quadD_1.dat",runtime);
  (*hsource)=(*hsource)+(*hbackgr);
  readbackgr(runname+"/quadD_2.dat",runtime);
  (*hsource)=(*hsource)+(*hbackgr);
  readbackgr(runname+"/quadD_3.dat",runtime);
  (*hsource)=(*hsource)+(*hbackgr);
  readbackgr(runname+"/quadD_4.dat",runtime);
  (*hsource)=(*hsource)+(*hbackgr);
  readbackgr(runname+"/quadD_5.dat",runtime);
  (*hsource)=(*hsource)+(*hbackgr);
  readbackgr(runname+"/quadD_6.dat",runtime);
  (*hsource)=(*hsource)+(*hbackgr);
  readbackgr(runname+"/quadD_7.dat",runtime);
  (*hsource)=(*hsource)+(*hbackgr);
  readbackgr(runname+"/quadD_8.dat",runtime);
  (*hsource)=(*hsource)+(*hbackgr);
  readbackgr(runname+"/quadD_9.dat",runtime);
  (*hsource)=(*hsource)+(*hbackgr);
  readbackgr(runname+"/quadD_10.dat",runtime);
  (*hsource)=(*hsource)+(*hbackgr);
  readbackgr(runname+"/quadD_11.dat",runtime);
  (*hsource)=(*hsource)+(*hbackgr);
  readbackgr(runname+"/quadD_12.dat",runtime);
  (*hsource)=(*hsource)+(*hbackgr);
  readbackgr(runname+"/quadD_13.dat",runtime);
  (*hsource)=(*hsource)+(*hbackgr);
  readbackgr(runname+"/quadD_14.dat",runtime);
  (*hsource)=(*hsource)+(*hbackgr);
  readbackgr(runname+"/quadD_15.dat",runtime);
  (*hsource)=(*hsource)+(*hbackgr);
  readbackgr(runname+"/quadD_16.dat",runtime);
  (*hsource)=(*hsource)+(*hbackgr);

  integralquadD=hsource->Integral(0,4096)-integralquadA-integralquadB-integralquadC;

  cout << "integrals:" << endl;
  cout << "quadA: " << integralquadA << endl;
  cout << "quadB: " << integralquadB << endl;
  cout << "quadC: " << integralquadC << endl;
  cout << "quadD: " << integralquadD << endl;
  cout << "ALL:   " << hsource->Integral(0,4096) << endl;

  cout << "hsource->Draw(); for displaying the spectrum" << endl;
//  hsource->Draw();

  /*


  
  TPaveText *pt = new TPaveText(0.65,0.7,0.85,0.85, "NDC");
  pt->AddText("run387");
  pt->AddText("sum of all TDC");
  //  pt->AddText("c");
  pt->Draw();
  */ 
}

int IntegratewithError(){

  float integral=0;
  float integralerror=0;

  for (int i=1;i<1200;i++){
    integral=integral+hsource->GetBinContent(i);
    integralerror=integralerror+(hsource->GetBinError(i))**2;
  }

  cout << "        integral = " << integral << endl;
  cout << "integralerror**2 = " << integralerror << endl;
  cout << "   integralerror = " << sqrt(integralerror) << endl;

  return 0;
}



int reset_all(){
  
  hbackgr = new TH1F("TDC sum","TDC sum",1000,0,1000-1);

  return 0;
}


int readbackgr(char* pFilename, int runsec) {
  
  char temp[900];
  TString title, xtitle, ytitle;
  TString xsizeS, ysizeS, specType;
  const char *tempchar;
  int xsize,ysize;
  float SpecTclVersion;
  int xch, ych;
  float value;
  char ch0;
  Int_t i=1;
  int exitflag=0;
  int specnum=0;
  

  // open the file
  ifstream file(pFilename, ios::in);
  
  file.getline(temp,900);
  while (exitflag == 0) {
    title = "";
    xtitle = "";
    ytitle = "";
    xsizeS = "";
    ysizeS = "";
    i=1;

    // unpacking the header 

    while (temp[i]!='"'){
      if (temp[i]=='-' || temp[i]=='.') {title += '_';
      i++;
      } else {title += temp[i]; 
      i++;
     }
    }

    i+=3;
    while (temp[i]!=' ' && temp[i]!=')'){xsizeS+=temp[i];i++;}
    if (temp[i]==' '){i++;
    while (temp[i]!=')'){ysizeS+=temp[i]; i++;}
    }
    tempchar = xsizeS;
    xsize = atoi(tempchar);
    tempchar = ysizeS;
    ysize = atoi(tempchar);    
    file.getline(temp,900);
    file >> SpecTclVersion;
    file.getline(temp,900);
    file >>  specType;
    file.getline(temp,900);
    file.getline(temp,900);
    i=2;
    while (temp[i]!='"'){xtitle += temp[i];i++;}
    i++;
    if (temp[i]==' '){i+=2;
      while (temp[i]!='"'){ytitle+=temp[i];i++;}
    }
    cout << "--------------------------------------------" << endl;
    cout << title << " "  << xsize << " " <<ysize << endl;
    cout << "SpecTcl Version " << SpecTclVersion ;
    cout << " Spectrum type " << specType << endl;
    cout << xtitle << " " << ytitle << endl;
    file.getline(temp,900);
    cout << temp << endl;
    file.getline(temp,900);
    cout << temp << endl;

    cout << "end of reading header" << endl;
    


    // here is where I define the spectrum based on 
       // the info in the header


      hbackgr = new TH1F(title,title,xsize,0,xsize-1);
      hbackgr->SetTitle("background");
      hbackgr->GetXaxis()->SetTitle(xtitle);

    
    
    xch =0;


    // here is where we fill the histogram

    while(xch != -1) {
      if (specType=="1" || specType=="g1") {
    	file >> ch0 >> xch >> ch0 >> value;
	hbackgr->Fill(xch,value/runsec);
	hbackgr->SetBinError(xch,sqrt(value)/runsec);
      } else {
	file >> ch0 >> xch >> ch0 >> value;
      }
    }
    file.getline(temp,900);
    file.getline(temp,900);
    int length = strlen(temp);
    if (length < 1) {exitflag=1;} 
  }
  file.close();







  //Draw h1[0]-histogram.

  hbackgr->Draw();
  //  gPad->SetLogy(1);
  //  gPad->Modified();



  return 0;
}


int readsource(char* pFilename, int runsec) {
  
  char temp[900];
  TString title, xtitle, ytitle;
  TString xsizeS, ysizeS, specType;
  const char *tempchar;
  int xsize,ysize;
  float SpecTclVersion;
  int xch, ych;
  float value;
  char ch0;
  Int_t i=1;
  int exitflag=0;
  int specnum=0;
  


  // open the file
  ifstream file(pFilename, ios::in);
  
  file.getline(temp,900);
  while (exitflag == 0) {
    title = "";
    xtitle = "";
    ytitle = "";
    xsizeS = "";
    ysizeS = "";
    i=1;

    // unpacking the header 

    while (temp[i]!='"'){
      if (temp[i]=='-' || temp[i]=='.') {title += '_';
      i++;
      } else {title += temp[i]; 
      i++;
     }
    }

    i+=3;
    while (temp[i]!=' ' && temp[i]!=')'){xsizeS+=temp[i];i++;}
    if (temp[i]==' '){i++;
    while (temp[i]!=')'){ysizeS+=temp[i]; i++;}
    }
    tempchar = xsizeS;
    xsize = atoi(tempchar);
    tempchar = ysizeS;
    ysize = atoi(tempchar);    
    file.getline(temp,900);
    file >> SpecTclVersion;
    file.getline(temp,900);
    file >>  specType;
    file.getline(temp,900);
    file.getline(temp,900);
    i=2;
    while (temp[i]!='"'){xtitle += temp[i];i++;}
    i++;
    if (temp[i]==' '){i+=2;
      while (temp[i]!='"'){ytitle+=temp[i];i++;}
    }
    cout << "--------------------------------------------" << endl;
    cout << title << " "  << xsize << " " <<ysize << endl;
    cout << "SpecTcl Version " << SpecTclVersion ;
    cout << " Spectrum type " << specType << endl;
    cout << xtitle << " " << ytitle << endl;
    file.getline(temp,900);
    cout << temp << endl;
    file.getline(temp,900);
    cout << temp << endl;

    cout << "end of reading header" << endl;
    


    // here is where I define the spectrum based on 
       // the info in the header


      hsource = new TH1F(title,title,xsize,0,xsize-1);
      hsource->GetXaxis()->SetTitle(xtitle);
      hsource->SetTitle("Run with source");    
      hcorr = new TH1F("corr.","corr.",xsize,0,xsize-1);

    
    
    xch =0;


    // here is where we fill the histogram

    while(xch != -1) {
      if (specType=="1" || specType=="g1") {
    	file >> ch0 >> xch >> ch0 >> value;
	hsource->Fill(xch,value/runsec);
	hsource->SetBinError(xch,sqrt(value)/runsec);
      } else {
	file >> ch0 >> xch >> ch0 >> value;
      }
    }
    file.getline(temp,900);
    file.getline(temp,900);
    int length = strlen(temp);
    if (length < 1) {exitflag=1;} 
  }
  file.close();


  //Draw histogram.

  hsource->Draw();
  //  gPad->SetLogy(1);
  //  gPad->Modified();



  return 0;
}
