// this is an example program of how to read an 
// ascii type spectrum file generated by SpecTcl
// currently it will work with a 1, 2, g1, g2, s type 
// spectrum from SpecTcl
// 
// Written by Mark Wallace (1/11/2003)

#include <fstream>
#include <iostream>

using namespace std;


  TH1F *hbackgr;
  TH1F *hsource;
  TH1F *hcorr;


int go(){

  readsource("run355/CRS/CRS_QDC_00!qdc00.dat",900);
  readbackgr("run345/CRS/CRS_QDC_00!qdc00.dat",900);
  corr();
  TPaveText *pt = new TPaveText(0.65,0.7,0.85,0.85, "NDC");
  pt->AddText("run355-run345");
  pt->AddText("HV=1500V");
  pt->AddText("ch00 - box I");
  pt->Draw();
  cout << endl << "            HV=1500V" << endl << endl;
  IntegScript();
}

int go_boxI(){

  //-----BOX I-----

  readsource("run355/CRS/CRS_QDC_00!qdc00.dat",900);
  readbackgr("run345/CRS/CRS_QDC_00!qdc00.dat",900);
  corr();
  TPaveText *pt = new TPaveText(0.65,0.7,0.85,0.85, "NDC");
  pt->AddText("run355-run345");
  pt->AddText("HV=1500V");
  pt->AddText("ch00 - box I");
  pt->Draw();
  cout << endl << "            HV=1500V" << endl << endl;
  IntegScript();

  readsource("run356/CRS/CRS_QDC_00!qdc00.dat",900);
  readbackgr("run346/CRS/CRS_QDC_00!qdc00.dat",900);
  corr();
  TPaveText *pt = new TPaveText(0.65,0.7,0.85,0.85, "NDC");
  pt->AddText("run356-run346");
  pt->AddText("HV=1550V");
  pt->AddText("ch00 - box I");
  pt->Draw();
  cout << endl << "            HV=1550V" << endl << endl;
  IntegScript();

  readsource("run357/CRS/CRS_QDC_00!qdc00.dat",900);
  readbackgr("run347/CRS/CRS_QDC_00!qdc00.dat",900);
  corr();
  TPaveText *pt = new TPaveText(0.65,0.7,0.85,0.85, "NDC");
  pt->AddText("run357-run347");
  pt->AddText("HV=1600V");
  pt->AddText("ch00 - box I");
  pt->Draw();
  cout << endl << "            HV=1600V" << endl << endl;
  IntegScript();

  readsource("run358/CRS/CRS_QDC_00!qdc00.dat",900);
  readbackgr("run348/CRS/CRS_QDC_00!qdc00.dat",900);
  corr();
  TPaveText *pt = new TPaveText(0.65,0.7,0.85,0.85, "NDC");
  pt->AddText("run358-run348");
  pt->AddText("HV=1650V");
  pt->AddText("ch00 - box I");
  pt->Draw();
  cout << endl << "            HV=1650V" << endl << endl;
  IntegScript();

  readsource("run359/CRS/CRS_QDC_00!qdc00.dat",900);
  readbackgr("run349/CRS/CRS_QDC_00!qdc00.dat",900);
  corr();
  TPaveText *pt = new TPaveText(0.65,0.7,0.85,0.85, "NDC");
  pt->AddText("run359-run349");
  pt->AddText("HV=1700V");
  pt->AddText("ch00 - box I");
  pt->Draw();
  cout << endl << "            HV=1700V" << endl << endl;
  IntegScript();

  readsource("run360/CRS/CRS_QDC_00!qdc00.dat",900);
  readbackgr("run362/CRS/CRS_QDC_00!qdc00.dat",900);
  corr();
  TPaveText *pt = new TPaveText(0.65,0.7,0.85,0.85, "NDC");
  pt->AddText("run360-run362");
  pt->AddText("HV=1750V");
  pt->AddText("ch00 - box I");
  pt->Draw();
  cout << endl << "            HV=1750V" << endl << endl;
  IntegScript();

  readsource("run365/CRS/CRS_QDC_00!qdc00.dat",900);
  readbackgr("run363/CRS/CRS_QDC_00!qdc00.dat",900);
  corr();
  TPaveText *pt = new TPaveText(0.65,0.7,0.85,0.85, "NDC");
  pt->AddText("run365-run363");
  pt->AddText("HV=1800V");
  pt->AddText("ch00 - box I");
  pt->Draw();
  cout << endl << "            HV=1800V" << endl << endl;
  IntegScript();




}
int go_boxII(){

  //-----BOX II-----

  readsource("run354/CRS/CRS_QDC_01!qdc01.dat",900);
  readbackgr("run345/CRS/CRS_QDC_01!qdc01.dat",900);
  corr();
  TPaveText *pt = new TPaveText(0.65,0.7,0.85,0.85, "NDC");
  pt->AddText("run354-run345");
  pt->AddText("HV=1500V");
  pt->AddText("ch00 - box II");
  pt->Draw();
  cout << endl << "            HV=1500V" << endl << endl;
  IntegScript();

  readsource("run353/CRS/CRS_QDC_01!qdc01.dat",900);
  readbackgr("run346/CRS/CRS_QDC_01!qdc01.dat",900);
  corr();
  TPaveText *pt = new TPaveText(0.65,0.7,0.85,0.85, "NDC");
  pt->AddText("run353-run346");
  pt->AddText("HV=1550V");
  pt->AddText("ch00 - box II");
  pt->Draw();
  cout << endl << "            HV=1550V" << endl << endl;
  IntegScript();

  readsource("run352/CRS/CRS_QDC_01!qdc01.dat",900);
  readbackgr("run347/CRS/CRS_QDC_01!qdc01.dat",900);
  corr();
  TPaveText *pt = new TPaveText(0.65,0.7,0.85,0.85, "NDC");
  pt->AddText("run352-run347");
  pt->AddText("HV=1600V");
  pt->AddText("ch00 - box II");
  pt->Draw();
  cout << endl << "            HV=1600V" << endl << endl;
  IntegScript();

  readsource("run351/CRS/CRS_QDC_01!qdc01.dat",900);
  readbackgr("run348/CRS/CRS_QDC_01!qdc01.dat",900);
  corr();
  TPaveText *pt = new TPaveText(0.65,0.7,0.85,0.85, "NDC");
  pt->AddText("run351-run348");
  pt->AddText("HV=1650V");
  pt->AddText("ch00 - box II");
  pt->Draw();
  cout << endl << "            HV=1650V" << endl << endl;
  IntegScript();

  readsource("run350/CRS/CRS_QDC_01!qdc01.dat",900);
  readbackgr("run349/CRS/CRS_QDC_01!qdc01.dat",900);
  corr();
  TPaveText *pt = new TPaveText(0.65,0.7,0.85,0.85, "NDC");
  pt->AddText("run350-run349");
  pt->AddText("HV=1700V");
  pt->AddText("ch00 - box II");
  pt->Draw();
  cout << endl << "            HV=1700V" << endl << endl;
  IntegScript();

  readsource("run361/CRS/CRS_QDC_01!qdc01.dat",900);
  readbackgr("run362/CRS/CRS_QDC_01!qdc01.dat",900);
  corr();
  TPaveText *pt = new TPaveText(0.65,0.7,0.85,0.85, "NDC");
  pt->AddText("run361-run362");
  pt->AddText("HV=1750V");
  pt->AddText("ch00 - box II");
  pt->Draw();
  cout << endl << "            HV=1750V" << endl << endl;
  IntegScript();

  readsource("run364/CRS/CRS_QDC_01!qdc01.dat",900);
  readbackgr("run363/CRS/CRS_QDC_01!qdc01.dat",900);
  corr();
  TPaveText *pt = new TPaveText(0.65,0.7,0.85,0.85, "NDC");
  pt->AddText("run365-run363");
  pt->AddText("HV=1800V");
  pt->AddText("ch00 - box II");
  pt->Draw();
  cout << endl << "            HV=1800V" << endl << endl;
  IntegScript();




}

int IntegScript() {

  float integralSOURCEvalue=0;
  float integralSOURCEerror=0;
  float integralBACKGRvalue=0;
  float integralBACKGRerror=0;
  float integralCORRvalue=0;
  float integralCORRerror=0;

  integralSOURCEvalue= hsource->Integral(0,5000);
  integralBACKGRvalue= hbackgr->Integral(0,5000);
  integralCORRvalue= hcorr->Integral(0,5000);

  for (int i=0;i<5000;i++){
    integralSOURCEerror=integralSOURCEerror+(hsource->GetBinError(i))**2;
    integralBACKGRerror=integralBACKGRerror+(hbackgr->GetBinError(i))**2;
    integralCORRerror=integralCORRerror+(hcorr->GetBinError(i))**2;
  }
  integralSOURCEerror=sqrt(integralSOURCEerror);
  integralBACKGRerror=sqrt(integralBACKGRerror);
  integralCORRerror=sqrt(integralCORRerror);

  cout << "integral SOUCRE " << integralSOURCEvalue << " +/- " << integralSOURCEerror << endl;
  cout << "integral BACKGR " << integralBACKGRvalue << " +/- " << integralBACKGRerror << endl;
  cout << "integral CORR   " << integralCORRvalue << " +/- " << integralCORRerror << endl;

}

int showbackgr(){

  readbackgr("run366/CRS/CRS_QDC_00.dat",44597);
  c1->Clear();
  c1->Divide(2,3);

  c1->cd(1);
  readbackgr("run366/CRS/CRS_QDC_00.dat",44597);
  gPad->SetLogy(1);
  gPad->Modified();

  c1->cd(3);
  readbackgr("run366/CRS/CRS_QDC_00!qdc00.dat",44597);

  c1->cd(5);
  readbackgr("run366/CRS/CRS_QDC_00!qdc01.dat",44597);


  c1->cd(2);
  readbackgr("run366/CRS/CRS_QDC_01.dat",44597);
  gPad->SetLogy(1);
  gPad->Modified();

  c1->cd(4);
  readbackgr("run366/CRS/CRS_QDC_01!qdc01.dat",44597);

  c1->cd(6);
  readbackgr("run366/CRS/CRS_QDC_01!qdc00.dat",44597);


}



int readbackgr(char* pFilename, int runsec) {
  
  char temp[900];
  TString title, xtitle, ytitle;
  TString xsizeS, ysizeS, specType;
  const char *tempchar;
  int xsize,ysize;
  float SpecTclVersion;
  int xch, ych;
  float value;
  char ch0;
  Int_t i=1;
  int exitflag=0;
  int specnum=0;
  

  // open the file
  ifstream file(pFilename, ios::in);
  
  file.getline(temp,900);
  while (exitflag == 0) {
    title = "";
    xtitle = "";
    ytitle = "";
    xsizeS = "";
    ysizeS = "";
    i=1;

    // unpacking the header 

    while (temp[i]!='"'){
      if (temp[i]=='-' || temp[i]=='.') {title += '_';
      i++;
      } else {title += temp[i]; 
      i++;
     }
    }

    i+=3;
    while (temp[i]!=' ' && temp[i]!=')'){xsizeS+=temp[i];i++;}
    if (temp[i]==' '){i++;
    while (temp[i]!=')'){ysizeS+=temp[i]; i++;}
    }
    tempchar = xsizeS;
    xsize = atoi(tempchar);
    tempchar = ysizeS;
    ysize = atoi(tempchar);    
    file.getline(temp,900);
    file >> SpecTclVersion;
    file.getline(temp,900);
    file >>  specType;
    file.getline(temp,900);
    file.getline(temp,900);
    i=2;
    while (temp[i]!='"'){xtitle += temp[i];i++;}
    i++;
    if (temp[i]==' '){i+=2;
      while (temp[i]!='"'){ytitle+=temp[i];i++;}
    }
    cout << "--------------------------------------------" << endl;
    cout << title << " "  << xsize << " " <<ysize << endl;
    cout << "SpecTcl Version " << SpecTclVersion ;
    cout << " Spectrum type " << specType << endl;
    cout << xtitle << " " << ytitle << endl;
    file.getline(temp,900);
    cout << temp << endl;
    file.getline(temp,900);
    cout << temp << endl;

    cout << "end of reading header" << endl;
    


    // here is where I define the spectrum based on 
       // the info in the header


      hbackgr = new TH1F(title,title,xsize,0,xsize-1);
      hbackgr->SetTitle("background");
      hbackgr->GetXaxis()->SetTitle(xtitle);

    
    
    xch =0;


    // here is where we fill the histogram

    while(xch != -1) {
      if (specType=="1" || specType=="g1") {
    	file >> ch0 >> xch >> ch0 >> value;
	hbackgr->Fill(xch,value/runsec);
	hbackgr->SetBinError(xch,sqrt(value)/runsec);
      } else {
	file >> ch0 >> xch >> ch0 >> value;
      }
    }
    file.getline(temp,900);
    file.getline(temp,900);
    int length = strlen(temp);
    if (length < 1) {exitflag=1;} 
  }
  file.close();







  //Draw h1[0]-histogram.

  hbackgr->Draw();
  //  gPad->SetLogy(1);
  //  gPad->Modified();



  return 0;
}


int readsource(char* pFilename, int runsec) {
  
  char temp[900];
  TString title, xtitle, ytitle;
  TString xsizeS, ysizeS, specType;
  const char *tempchar;
  int xsize,ysize;
  float SpecTclVersion;
  int xch, ych;
  float value;
  char ch0;
  Int_t i=1;
  int exitflag=0;
  int specnum=0;
  


  // open the file
  ifstream file(pFilename, ios::in);
  
  file.getline(temp,900);
  while (exitflag == 0) {
    title = "";
    xtitle = "";
    ytitle = "";
    xsizeS = "";
    ysizeS = "";
    i=1;

    // unpacking the header 

    while (temp[i]!='"'){
      if (temp[i]=='-' || temp[i]=='.') {title += '_';
      i++;
      } else {title += temp[i]; 
      i++;
     }
    }

    i+=3;
    while (temp[i]!=' ' && temp[i]!=')'){xsizeS+=temp[i];i++;}
    if (temp[i]==' '){i++;
    while (temp[i]!=')'){ysizeS+=temp[i]; i++;}
    }
    tempchar = xsizeS;
    xsize = atoi(tempchar);
    tempchar = ysizeS;
    ysize = atoi(tempchar);    
    file.getline(temp,900);
    file >> SpecTclVersion;
    file.getline(temp,900);
    file >>  specType;
    file.getline(temp,900);
    file.getline(temp,900);
    i=2;
    while (temp[i]!='"'){xtitle += temp[i];i++;}
    i++;
    if (temp[i]==' '){i+=2;
      while (temp[i]!='"'){ytitle+=temp[i];i++;}
    }
    cout << "--------------------------------------------" << endl;
    cout << title << " "  << xsize << " " <<ysize << endl;
    cout << "SpecTcl Version " << SpecTclVersion ;
    cout << " Spectrum type " << specType << endl;
    cout << xtitle << " " << ytitle << endl;
    file.getline(temp,900);
    cout << temp << endl;
    file.getline(temp,900);
    cout << temp << endl;

    cout << "end of reading header" << endl;
    


    // here is where I define the spectrum based on 
       // the info in the header


      hsource = new TH1F(title,title,xsize,0,xsize-1);
      hsource->GetXaxis()->SetTitle(xtitle);
      hsource->SetTitle("Run with source");    
      hcorr = new TH1F("corr.","corr.",xsize,0,xsize-1);

    
    
    xch =0;


    // here is where we fill the histogram

    while(xch != -1) {
      if (specType=="1" || specType=="g1") {
    	file >> ch0 >> xch >> ch0 >> value;
	hsource->Fill(xch,value/runsec);
	hsource->SetBinError(xch,sqrt(value)/runsec);
      } else {
	file >> ch0 >> xch >> ch0 >> value;
      }
    }
    file.getline(temp,900);
    file.getline(temp,900);
    int length = strlen(temp);
    if (length < 1) {exitflag=1;} 
  }
  file.close();


  //Draw histogram.

  hsource->Draw();
  //  gPad->SetLogy(1);
  //  gPad->Modified();



  return 0;
}


int corr() {

   (*hcorr) = (*hsource) - (*hbackgr);
   hcorr->SetTitle("Run with source background corrected");

   hcorr->Draw();
   c1->Clear();

   c1->Divide(1,3);
   c1->cd(1);
   gStyle->SetOptStat(1000001);
   hsource->Draw();
   //   gPad->SetLogy(1);
   //   gPad->Modified();
   c1->cd(2);
   gStyle->SetOptStat(1000001);
   hbackgr->Draw();
   //   gPad->SetLogy(1);
   //   gPad->Modified();
   c1->cd(3);
   gStyle->SetOptStat(1000001);
   hcorr->Draw();
   //   gPad->SetLogy(1);
   //   gPad->Modified(); 



}



int write_file(char *pFile){
  TObjArray Hlist(0);
  Hlist.Add(gDirectory->GetList());
  TFile ff(pFile,"recreate");
  Hlist.Write();
  ff.Close();
  return 0;
}
