// this is an example program of how to read an 
// ascii type spectrum file generated by SpecTcl
// currently it will work with a 1, 2, g1, g2, s type 
// spectrum from SpecTcl
// 
// Written by Mark Wallace (1/11/2003)

#include <fstream>
#include <iostream>

using namespace std;


  TH1F *h1[1000];
  TH2F *h2[1000];


int display(char* pFilename) {
  
  char temp[900];
  TString title, xtitle, ytitle;
  TString xsizeS, ysizeS, specType;
  const char *tempchar;
  int xsize,ysize;
  float SpecTclVersion;
  int xch, ych;
  float value;
  char ch0;
  Int_t i=1;
  int exitflag=0;
  int specnum=0;
  
  // define an array of histograms to be filled
  //  TH1F *h1[1000];
  //  TH2F *h2[1000];

  // open the file
  ifstream file(pFilename, ios::in);
  
  file.getline(temp,900);
  while (exitflag == 0) {
    title = "";
    xtitle = "";
    ytitle = "";
    xsizeS = "";
    ysizeS = "";
    i=1;

    // unpacking the header 

    while (temp[i]!='"'){
      if (temp[i]=='-' || temp[i]=='.') {title += '_';
      i++;
      } else {title += temp[i]; 
      i++;
     }
    }

    i+=3;
    while (temp[i]!=' ' && temp[i]!=')'){xsizeS+=temp[i];i++;}
    if (temp[i]==' '){i++;
    while (temp[i]!=')'){ysizeS+=temp[i]; i++;}
    }
    tempchar = xsizeS;
    xsize = atoi(tempchar);
    tempchar = ysizeS;
    ysize = atoi(tempchar);    
    file.getline(temp,900);
    file >> SpecTclVersion;
    file.getline(temp,900);
    file >>  specType;
    file.getline(temp,900);
    file.getline(temp,900);
    i=2;
    while (temp[i]!='"'){xtitle += temp[i];i++;}
    i++;
    if (temp[i]==' '){i+=2;
      while (temp[i]!='"'){ytitle+=temp[i];i++;}
    }
    cout << "--------------------------------------------" << endl;
    cout << title << " "  << xsize << " " <<ysize << endl;
    cout << "SpecTcl Version " << SpecTclVersion ;
    cout << " Spectrum type " << specType << endl;
    cout << xtitle << " " << ytitle << endl;
    file.getline(temp,900);
    cout << temp << endl;
    file.getline(temp,900);
    cout << temp << endl;

    cout << "end of reading header" << endl;
    


    // here is where I define the spectrum based on 
    // the info in the header

    if (specType == "1") {
      h1[specnum] = new TH1F(title,title,xsize,0,xsize-1);
      h1[specnum]->GetXaxis()->SetTitle(xtitle);
    }
    if (specType == "2") {
      h2[specnum] = new TH2F(title,title,xsize,0,xsize-1
			     ,ysize,0,ysize-1);
      h2[specnum]->GetXaxis()->SetTitle(xtitle);
      h2[specnum]->GetYaxis()->SetTitle(ytitle);
    }
    if (specType == "g1") {
      h1[specnum] = new TH1F(title,title,xsize,0,xsize-1);
      h1[specnum]->GetXaxis()->SetTitle("gamma 1d");
    }
    if (specType == "g2") {
      h2[specnum] = new TH2F(title,title,xsize,0,xsize-1
			     ,ysize,0,ysize-1);
      h2[specnum]->GetXaxis()->SetTitle("gamma 2d");
    }
    if (specType == "s") {
      h2[specnum] = new TH2F(title,title,xsize,0,xsize-1
			     ,ysize,0,ysize-1);
      h2[specnum]->GetXaxis()->SetTitle("Summary");
    }
    if (specType == "b") {
      cout << "Bit spectrum not working yet" << endl;
    }

    
    xch =0;
    ych =0;

    // here is where we fill the histogram

    while(xch != -1) {
      if (specType=="1" || specType=="g1") {
    	file >> ch0 >> xch >> ch0 >> value;
	h1[specnum]->Fill(xch,value);
      } else if (specType=="2" || specType=="g2" || specType=="s"){
	file >> ch0 >> xch >> ych >> ch0 >> value;
	h2[specnum]->Fill(xch,ych,value);
      } else {
	file >> ch0 >> xch >> ch0 >> value;
      }
    }
    file.getline(temp,900);
    file.getline(temp,900);
    int length = strlen(temp);
    specnum++;
    if (length < 1) {exitflag=1;} 
  }
  file.close();


  //Draw h1[0]-histogram.

  h1[0]->SetYTitle("absolute counts");
  h1[0]->SetXTitle("ADC bin");
  h1[0]->SetAxisRange(0,2000);
  h1[0]->Draw();
//  gPad->SetLogy(1);
//  gPad->Modified();
//  gStyle->SetOptStat(0);




  return 0;
}

int pics(TString runname, TString spectrum, TString quad, TString extention){

  cout << runname + spectrum+quad+"9"+extention << endl;

  display(runname + spectrum+quad+"1"+extention);
  c1->SaveAs(runname + spectrum+quad+"1"+extention+".jpg");
  display(runname + spectrum+quad+"2"+extention);
  c1->SaveAs(runname + spectrum+quad+"2"+extention+".jpg");
  display(runname + spectrum+quad+"3"+extention);
  c1->SaveAs(runname + spectrum+quad+"3"+extention+".jpg");
  display(runname + spectrum+quad+"4"+extention);
  c1->SaveAs(runname + spectrum+quad+"4"+extention+".jpg");
  display(runname + spectrum+quad+"5"+extention);
  c1->SaveAs(runname + spectrum+quad+"5"+extention+".jpg");
  display(runname + spectrum+quad+"6"+extention);
  c1->SaveAs(runname + spectrum+quad+"6"+extention+".jpg");
  display(runname + spectrum+quad+"7"+extention);
  c1->SaveAs(runname + spectrum+quad+"7"+extention+".jpg");
  display(runname + spectrum+quad+"8"+extention);
  c1->SaveAs(runname + spectrum+quad+"8"+extention+".jpg");
  display(runname + spectrum+quad+"9"+extention);
  c1->SaveAs(runname + spectrum+quad+"9"+extention+".jpg");
  display(runname + spectrum+quad+"10"+extention);
  c1->SaveAs(runname + spectrum+quad+"10"+extention+".jpg");
  display(runname + spectrum+quad+"11"+extention);
  c1->SaveAs(runname + spectrum+quad+"11"+extention+".jpg");
  display(runname + spectrum+quad+"12"+extention);
  c1->SaveAs(runname + spectrum+quad+"12"+extention+".jpg");
  display(runname + spectrum+quad+"13"+extention);
  c1->SaveAs(runname + spectrum+quad+"13"+extention+".jpg");
  display(runname + spectrum+quad+"14"+extention);
  c1->SaveAs(runname + spectrum+quad+"14"+extention+".jpg");
  display(runname + spectrum+quad+"15"+extention);
  c1->SaveAs(runname + spectrum+quad+"15"+extention+".jpg");
  display(runname + spectrum+quad+"16"+extention);
  c1->SaveAs(runname + spectrum+quad+"16"+extention+".jpg");

}

int go(TString runname, TString spectrum){

  TString extention="";

  if (spectrum=="/ADC/") { extention=".dat"; }
  if (spectrum=="/TDC/") { extention=".dat"; }
  if (spectrum=="/ADC!TDC/") { extention="!TDC.dat"; }
  if (spectrum=="/ADC!TDC_ch2/") { extention="!TDC_ch2.dat"; }

  pics(runname,spectrum,"quadA_",extention);
  pics(runname,spectrum,"quadB_",extention);
  pics(runname,spectrum,"quadC_",extention);
  pics(runname,spectrum,"quadD_",extention);
}

int goall(){

//  go("run415","/ADC/");
//  go("run415","/ADC!TDC/");
//  go("run415","/ADC!TDC_ch2/");

//  go("run417","/ADC/");
  go("run417","/ADC!TDC/");
//  go("run417","/ADC!TDC_ch2/");

}


int goagain(){

  display("run417/ADC/quadB_4.dat");
  c1->SaveAs("run417/ADC/quadB_4.dat.jpg");
  display("run417/ADC!TDC/quadB_4!TDC.dat");
  c1->SaveAs("run417/ADC!TDC/quadB_4!TDC.dat.jpg");
  display("run417/ADC!TDC_ch2/quadB_4!TDC_ch2.dat");
  c1->SaveAs("run417/ADC!TDC_ch2/quadB_4!TDC_ch2.dat.jpg");

}



int write_file(char *pFile){
  TObjArray Hlist(0);
  Hlist.Add(gDirectory->GetList());
  TFile ff(pFile,"recreate");
  Hlist.Write();
  ff.Close();
  return 0;
}
