// this is an example program of how to read an 
// ascii type spectrum file generated by SpecTcl
// currently it will work with a 1, 2, g1, g2, s type 
// spectrum from SpecTcl
// 
// Written by Mark Wallace (1/11/2003)

#include <fstream>
#include <iostream>

using namespace std;


  TH1F *hbackgr;
  TH1F *hsource;
  TH1F *hcorr;



int readsource(char* pFilename, int runsec) {
  
  char temp[900];
  TString title, xtitle, ytitle;
  TString xsizeS, ysizeS, specType;
  const char *tempchar;
  int xsize,ysize;
  float SpecTclVersion;
  int xch, ych;
  float value;
  char ch0;
  Int_t i=1;
  int exitflag=0;
  int specnum=0;
  


  // open the file
  ifstream file(pFilename, ios::in);
  
  file.getline(temp,900);
  while (exitflag == 0) {
    title = "";
    xtitle = "";
    ytitle = "";
    xsizeS = "";
    ysizeS = "";
    i=1;

    // unpacking the header 

    while (temp[i]!='"'){
      if (temp[i]=='-' || temp[i]=='.') {title += '_';
      i++;
      } else {title += temp[i]; 
      i++;
     }
    }

    i+=3;
    while (temp[i]!=' ' && temp[i]!=')'){xsizeS+=temp[i];i++;}
    if (temp[i]==' '){i++;
    while (temp[i]!=')'){ysizeS+=temp[i]; i++;}
    }
    tempchar = xsizeS;
    xsize = atoi(tempchar);
    tempchar = ysizeS;
    ysize = atoi(tempchar);    
    file.getline(temp,900);
    file >> SpecTclVersion;
    file.getline(temp,900);
    file >>  specType;
    file.getline(temp,900);
    file.getline(temp,900);
    i=2;
    while (temp[i]!='"'){xtitle += temp[i];i++;}
    i++;
    if (temp[i]==' '){i+=2;
      while (temp[i]!='"'){ytitle+=temp[i];i++;}
    }
    cout << "--------------------------------------------" << endl;
    cout << title << " "  << xsize << " " <<ysize << endl;
    cout << "SpecTcl Version " << SpecTclVersion ;
    cout << " Spectrum type " << specType << endl;
    cout << xtitle << " " << ytitle << endl;
    file.getline(temp,900);
    cout << temp << endl;
    file.getline(temp,900);
    cout << temp << endl;

    cout << "end of reading header" << endl;
    


    // here is where I define the spectrum based on 
       // the info in the header


      hsource = new TH1F("Moderation time","Moderation time",120,0,600);
      hsource->GetXaxis()->SetTitle("time in micro sec.");
      hsource->SetTitle("Moderation time (experimental data)");    


    
    
    xch =0;


    // here is where we fill the histogram

    while(xch != -1) {
      if (specType=="1" || specType=="g1") {
    	file >> ch0 >> xch >> ch0 >> value;
	hsource->Fill(xch*0.2,value/runsec);
	hsource->SetBinError(xch*0.2,sqrt(value)/runsec);
      } else {
	file >> ch0 >> xch >> ch0 >> value;
      }
    }
    file.getline(temp,900);
    file.getline(temp,900);
    int length = strlen(temp);
    if (length < 1) {exitflag=1;} 
  }
  file.close();


  //Draw histogram.
  gStyle->SetOptStat(1000001);
  hsource->Draw();
  //  gPad->SetLogy(1);
  //  gPad->Modified();



  return 0;
}



